version: 2.1

jobs:
  build:
    docker:
      - image: node:alpine
    working_directory: ~/twitter-clone
    steps:
      - attach_workspace:
          at: ~/twitter-clone
      - checkout
      - run:
          name: "setup the project"
          command: yarn install
      - persist_to_workspace:
          root: .
          paths:
            - "."
  test:
    docker:
      - image: cimg/node:lts-browsers
    working_directory: ~/twitter-clone
    steps:
      - attach_workspace:
          at: ~/twitter-clone
      - run:
          name: "run tests"
          command: yarn test:unit
workflows:
  test_things:
    jobs:
      - build
      - test:
          requires:
            - build
